In [ ]:
! pip install tensorflow

In [46]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_gpu_available())

2.15.0
False


In [47]:
# Constant in tensorflow
a = tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [48]:
b = tf.constant(1, dtype=tf.int64)
b.numpy()

1

In [49]:
c = tf.constant([[1,2],[3,4]])
c, c.numpy()

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 array([[1, 2],
        [3, 4]]))

In [50]:
c.shape

TensorShape([2, 2])

### Genrate ones of particular shape

In [51]:
print(tf.ones((3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [52]:
tf.add(tf.ones((3,2)), tf.ones((3,2)))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32)>

### Random constant

In [53]:
tf.random.normal((3,2), mean=0, stddev=1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.4087416, -0.1157558],
       [ 0.3003348,  1.262337 ],
       [-0.6422548, -1.3219199]], dtype=float32)>

### Variables

```A variable is a special tensor that is used to store variable values and needs to be initialized with some values```

In [54]:
var = 23 # python variable
var0 = tf.Variable(0) # Rank 0
var1 = tf.Variable([1,2]) # Rank 1
var2 = tf.Variable([[1,2],[3,4]]) # Rank 2
var3 = tf.Variable([[[1,2],[3,4]],[[5,6],[7,8]]]) # Rank 3
var0, var1, var2, var3

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>)

TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

### To reassign the value

In [55]:
var0.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [56]:
var0.numpy()

2

In [57]:
initial_value = tf.random.normal((2,2))
a  = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.2626659 ,  0.84562516],
       [-0.88061804,  0.06464776]], dtype=float32)>


We can assign "=" With assign (value), or assign_add (value) With "+=" or assjgn_sub (value) with "-="

In [58]:
new_value = tf.random.normal((2,2))
a.assign_add(new_value)

## Checck weather the value is updated or not
for i in range(2):
  for j in range(2):
    assert a[i,j] == initial_value[i,j] + new_value[i,j]

In [65]:
import tensorflow as tf

initial_value = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.Variable(initial_value)
new_value = tf.random.normal((2,2))
b.assign_sub(new_value)

for i in range(2):
    for j in range(2):
        assert b[i,j].numpy() == initial_value[i,j].numpy() - new_value[i,j].numpy()

print("Assertion passed successfully.")

Assertion passed successfully.


In [66]:
b.numpy()

array([[1.6003227, 0.7174443],
       [1.1362963, 3.087298 ]], dtype=float32)

### Shaping a Tensor
Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.


In [73]:
tensor = tf.Variable([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

In [74]:
tensor.shape

TensorShape([2, 2, 3])

In [76]:
tensor1 = tf.reshape(tensor, [2, 6])
tensor2 = tf.reshape(tensor, [1, 12])
tensor1, tensor2

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])>,
 <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])>)

### Ranking (dimension) of a tensor

The rank of a tensor is the number of dimensions it has. that is, the nunber of indices that are required to specify any particular
element Of that tensor.

In [77]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Specifying an element of a tensor

In [79]:
tensor.numpy()

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [81]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3, tensor3.numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=8>, 8)

### Casting a tensor to numpy/python variable

In [82]:
print(tensor.numpy())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [83]:
tensor[0, 1, 2].numpy()

5

### Finding size (number of elements) of a tensor

In [85]:
tf.size(tensor).numpy(), tf.shape(tensor)

(12, <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3])>)

In [86]:
tensor.dtype

tf.int32

### Tensorflow mathematical operations
Can be used as numpy for artificial operations Tensorflow can not execute these operations on the GPU or TPU

In [88]:
a = tf.random.normal([2, 2])
b = tf.random.normal([2, 2])
c = a + b
d = tf.square(c)
e = tf.exp(d)
a, "/n",b, "/n", c, "/n", d, "/n", e

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.40172255, -0.4053606 ],
        [ 1.021875  ,  0.68157464]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7384434 ,  0.22653873],
        [-0.9167601 , -0.96705896]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.1401659 , -0.17882188],
        [ 0.10511494, -0.2854843 ]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.2999784 , 0.03197726],
        [0.01104915, 0.08150129]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3.6692173, 1.0324941],
        [1.0111104, 1.0849146]], dtype=float32)>)

### Elementwise primitive tensor operations

In [94]:
tensor - tensor, tensor * tensor, tensor / tensor, tensor + tensor

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[  0,   1,   4],
         [  9,  16,  25]],
 
        [[ 36,  49,  64],
         [ 81, 100, 121]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float64, numpy=
 array([[[nan,  1.,  1.],
         [ 1.,  1.,  1.]],
 
        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 0,  2,  4],
         [ 6,  8, 10]],
 
        [[12, 14, 16],
         [18, 20, 22]]])>)

### Broadcasting
- Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.
- The simplest example that of a tensor by a scalar:

In [95]:
tensor * 5

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  5, 10],
        [15, 20, 25]],

       [[30, 35, 40],
        [45, 50, 55]]])>

### Transpose Matrix Multiplicatin

In [96]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [97]:
tf.transpose(matrix1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

In [99]:
tf.matmul(tf.transpose(matrix1), matrix2) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 30],
       [38, 44]])>

### Casting a tensor to another tensor datatype

In [100]:
tf.cast(matrix1, tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

### With Truncation

In [102]:
j = tf.cast(tf.constant([1.330, 2.2220]), tf.int32)
j

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

### Declaring Ragged tensors

- A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths. There are a variety of mothods for declaring ragged arrays, tho simplest being a constant ragged array.

In [103]:
ragged = tf.ragged.constant([[9, 7, 8, 0], [], [1, 3, 2, 4, 6], [11, 22]])

In [109]:
ragged, ragged[0,:], ragged[2 , 1:4], ragged[1].numpy()

(<tf.RaggedTensor [[9, 7, 8, 0], [], [1, 3, 2, 4, 6], [11, 22]]>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 7, 8, 0])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 4])>,
 array([], dtype=int32))

### Finding squared difference between two tensors

In [111]:
varx = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
vary = 5

varz = tf.math.squared_difference(varx, vary)
varz

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([16,  9,  4,  1,  0,  1,  4,  9, 16, 25])>

The Python variables, varx and vary. are cast into tensors and that vary is then broadcast across varx in this example. So. for
example. the first calculation is (1- 5)2 = 16.

### Finding the Mean

The following is the signature of tf.reduce-mean().

Note that this is equivalent to np.mean, except that it infers the return datatype trom the input tensor, whereas
np.mean allows you to specify tho output type (defaulting to float64)

In [115]:
number  = tf.constant([[1, 2], [3, 4]])

## Mean along all axis
tf.reduce_mean(input_tensor=number, axis=None, keepdims=False)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [116]:
## Mean along all columns
tf.reduce_mean(input_tensor=number, axis=0, keepdims=False)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

When keepdims is True, the reduced axis is retained With a length Of l:

In [117]:
tf.reduce_mean(input_tensor=number, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>