In [ ]:
! pip install tensorflow

In [171]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_gpu_available())

2.15.0
False


In [172]:
# Constant in tensorflow
a = tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [173]:
b = tf.constant(1, dtype=tf.int64)
b.numpy()

1

In [174]:
c = tf.constant([[1,2],[3,4]])
c, c.numpy()

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 array([[1, 2],
        [3, 4]]))

In [175]:
c.shape

TensorShape([2, 2])

### Genrate ones of particular shape

In [176]:
print(tf.ones((3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [177]:
tf.add(tf.ones((3,2)), tf.ones((3,2)))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32)>

### Random constant

In [178]:
tf.random.normal((3,2), mean=0, stddev=1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8089824 ,  1.1437266 ],
       [ 0.37968534,  0.95578766],
       [-0.37827846,  0.78194255]], dtype=float32)>

### Variables

```A variable is a special tensor that is used to store variable values and needs to be initialized with some values```

In [179]:
var = 23 # python variable
var0 = tf.Variable(0) # Rank 0
var1 = tf.Variable([1,2]) # Rank 1
var2 = tf.Variable([[1,2],[3,4]]) # Rank 2
var3 = tf.Variable([[[1,2],[3,4]],[[5,6],[7,8]]]) # Rank 3
var0, var1, var2, var3

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>)

TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

### To reassign the value

In [180]:
var0.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [181]:
var0.numpy()

2

In [182]:
initial_value = tf.random.normal((2,2))
a  = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.158006  , -0.25985676],
       [-0.59844977, -0.5830384 ]], dtype=float32)>


We can assign "=" With assign (value), or assign_add (value) With "+=" or assjgn_sub (value) with "-="

In [183]:
new_value = tf.random.normal((2,2))
a.assign_add(new_value)

## Checck weather the value is updated or not
for i in range(2):
  for j in range(2):
    assert a[i,j] == initial_value[i,j] + new_value[i,j]

In [184]:
import tensorflow as tf

initial_value = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.Variable(initial_value)
new_value = tf.random.normal((2,2))
b.assign_sub(new_value)

for i in range(2):
    for j in range(2):
        assert b[i,j].numpy() == initial_value[i,j].numpy() - new_value[i,j].numpy()

print("Assertion passed successfully.")

Assertion passed successfully.


In [185]:
b.numpy()

array([[-0.61260533,  2.1219614 ],
       [ 2.0655293 ,  4.437322  ]], dtype=float32)

### Shaping a Tensor
Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.


In [186]:
tensor = tf.Variable([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

In [187]:
tensor.shape

TensorShape([2, 2, 3])

In [188]:
tensor1 = tf.reshape(tensor, [2, 6])
tensor2 = tf.reshape(tensor, [1, 12])
tensor1, tensor2

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])>,
 <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])>)

### Ranking (dimension) of a tensor

The rank of a tensor is the number of dimensions it has. that is, the nunber of indices that are required to specify any particular
element Of that tensor.

In [189]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Specifying an element of a tensor

In [190]:
tensor.numpy()

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [191]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3, tensor3.numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=8>, 8)

### Casting a tensor to numpy/python variable

In [192]:
print(tensor.numpy())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [193]:
tensor[0, 1, 2].numpy()

5

### Finding size (number of elements) of a tensor

In [194]:
tf.size(tensor).numpy(), tf.shape(tensor)

(12, <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3])>)

In [195]:
tensor.dtype

tf.int32

### Tensorflow mathematical operations
Can be used as numpy for artificial operations Tensorflow can not execute these operations on the GPU or TPU

In [196]:
a = tf.random.normal([2, 2])
b = tf.random.normal([2, 2])
c = a + b
d = tf.square(c)
e = tf.exp(d)
a, "/n",b, "/n", c, "/n", d, "/n", e

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.28425562, -0.49051556],
        [ 0.7645078 ,  0.41764784]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.6636649 ,  0.8449321 ],
        [ 0.25897932, -0.57181484]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.3794093 ,  0.35441652],
        [ 1.0234871 , -0.154167  ]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.90277   , 0.12561107],
        [1.0475259 , 0.02376746]], dtype=float32)>,
 '/n',
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[6.70444  , 1.133841 ],
        [2.8505898, 1.0240521]], dtype=float32)>)

### Elementwise primitive tensor operations

In [197]:
tensor - tensor, tensor * tensor, tensor / tensor, tensor + tensor

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[  0,   1,   4],
         [  9,  16,  25]],
 
        [[ 36,  49,  64],
         [ 81, 100, 121]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float64, numpy=
 array([[[nan,  1.,  1.],
         [ 1.,  1.,  1.]],
 
        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 0,  2,  4],
         [ 6,  8, 10]],
 
        [[12, 14, 16],
         [18, 20, 22]]])>)

### Broadcasting
- Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.
- The simplest example that of a tensor by a scalar:

In [198]:
tensor * 5

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  5, 10],
        [15, 20, 25]],

       [[30, 35, 40],
        [45, 50, 55]]])>

### Transpose Matrix Multiplicatin

In [199]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [200]:
tf.transpose(matrix1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

In [201]:
tf.matmul(tf.transpose(matrix1), matrix2) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 30],
       [38, 44]])>

### Casting a tensor to another tensor datatype

In [202]:
tf.cast(matrix1, tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

### With Truncation

In [203]:
j = tf.cast(tf.constant([1.330, 2.2220]), tf.int32)
j

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

### Declaring Ragged tensors

- A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths. There are a variety of mothods for declaring ragged arrays, tho simplest being a constant ragged array.

In [204]:
ragged = tf.ragged.constant([[9, 7, 8, 0], [], [1, 3, 2, 4, 6], [11, 22]])

In [205]:
ragged, ragged[0,:], ragged[2 , 1:4], ragged[1].numpy()

(<tf.RaggedTensor [[9, 7, 8, 0], [], [1, 3, 2, 4, 6], [11, 22]]>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 7, 8, 0])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 4])>,
 array([], dtype=int32))

### Finding squared difference between two tensors

In [206]:
varx = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
vary = 5

varz = tf.math.squared_difference(varx, vary)
varz

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([16,  9,  4,  1,  0,  1,  4,  9, 16, 25])>

The Python variables, varx and vary. are cast into tensors and that vary is then broadcast across varx in this example. So. for
example. the first calculation is (1- 5)2 = 16.

### Finding the Mean

The following is the signature of tf.reduce_mean().

Note that this is equivalent to np.mean, except that it infers the return datatype trom the input tensor, whereas
np.mean allows you to specify tho output type (defaulting to float64)

In [207]:
number  = tf.constant([[1, 2], [3, 4]])

## Mean along all axis
tf.reduce_mean(input_tensor=number, axis=None, keepdims=False)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [208]:
number.numpy()[1][1]


4

In [209]:
number.numpy()

array([[1, 2],
       [3, 4]])

In [210]:
## Mean along all columns (x-axis)
tf.reduce_mean(input_tensor=number, axis=1, keepdims=False)
# case1.numpy()[1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

When keepdims is True, the reduced axis is retained With a length of 1:

In [211]:
## Mean along all columns (x-axis)
tf.reduce_mean(input_tensor=number, axis=1, keepdims=True)
# case2.numpy()[0][1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]])>

In [212]:
## Mean along all rows (y-axis)
tf.reduce_mean(input_tensor=number, axis=0, keepdims=True)


<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>

#### Setting the Seed

In [213]:
ran1 = tf.random.normal([2, 2], mean=0, stddev=1)
ran2 = tf.random.normal([2, 2], mean=0, stddev=1)

ran1, ran2 

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.41427493,  0.27209428],
        [ 0.18780643, -1.0397136 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.10532369,  2.5562282 ],
        [-1.5410595 , -1.4889685 ]], dtype=float32)>)

In [230]:
tf.random.set_seed(11)
ran1 = tf.random.normal([2, 2], mean=0, stddev=1)
ran2 = tf.random.normal([2, 2], mean=0, stddev=1)
ran1, ran2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.5229472 ,  0.66954476],
        [-0.6424697 ,  1.4300429 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.35981855,  1.0180439 ],
        [-2.0297976 , -0.7807032 ]], dtype=float32)>)

In [233]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

dice_sum = dice1 + dice2

resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
resulting_matrix

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 3,  4,  7],
       [ 4,  5,  9],
       [ 1,  1,  2],
       [ 5,  5, 10],
       [ 6,  2,  8],
       [ 6,  6, 12],
       [ 6,  5, 11],
       [ 1,  4,  5],
       [ 6,  3,  9],
       [ 4,  4,  8]])>

### Finding the indices of the largest and smallest element

In [267]:
t5 = tf.constant([1, 2, 3, 4, 5, 6, 3, 0.1, 9])

i = tf.argmax(t5)

t5[i].numpy()

9.0

In [268]:
i = tf.argmin(t5)

print(t5[i].numpy())

0.1


In [272]:
t6 = tf.reshape(t5, [3, 3])
i = tf.argmax(t6, axis=0) # max arg down rows (y-axis) sare row y axis pe max value ki index
print(t6, i)

tf.Tensor(
[[1.  2.  3. ]
 [4.  5.  6. ]
 [3.  0.1 9. ]], shape=(3, 3), dtype=float32) tf.Tensor([1 1 2], shape=(3,), dtype=int64)


In [271]:
t6 = tf.reshape(t5, [3, 3])
i = tf.argmax(t6, axis=1) # max arg across columns (x-axis) ek row mei max value
print(t6, i)

tf.Tensor(
[[1.  2.  3. ]
 [4.  5.  6. ]
 [3.  0.1 9. ]], shape=(3, 3), dtype=float32) tf.Tensor([2 2 2], shape=(3,), dtype=int64)


In [280]:
t6 = tf.reshape(t5, [3, 3])
i = tf.argmin(t6, axis=1).numpy() # min arg across columns (x-axis) ek row mei max value
print(t6, i)

tf.Tensor(
[[1.  2.  3. ]
 [4.  5.  6. ]
 [3.  0.1 9. ]], shape=(3, 3), dtype=float32) [0 0 1]


In [281]:
t6[i[0], 0].numpy(), t6[i[1], 1].numpy(), t6[i[2], 2].numpy()

(1.0, 2.0, 6.0)

### Saving and restoring tensor values using a checkpoint

In [277]:
variable = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
checkpoint = tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
e = checkpoint.restore(save_path)
variable, e

(<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>,
 <tensorflow.python.checkpoint.checkpoint.CheckpointLoadStatus at 0x1e6ca746490>)

### Using tf.function
- tf.function is a function that will take a Python function and return a TensorFlow graph. 
- The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). 
- tf.function is new to tensorflow 2

In [284]:
def f1(x, y):
  return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y ** 2)

## Making a tensorflow function which returns ternsorflow graph
f2 = tf.function(f1)

x = tf.constant([4, 5])
y = tf.constant([1, 2])

## f1 and f 2 return the same value, but f 2 executes as a TensorFlow graph
assert f1(x, y).numpy() == f2(x, y).numpy()

### Calculate the Gradient

#### Gradient tape
- Another difference from numpy is that it can automatically track the gradient of any variable.
- Open one GradientTape and tape.watch() track variables through

In [285]:
a = tf.random.normal([2, 2])
b = tf.random.normal([2, 2])

with tf.GradientTape() as tape:
  tape.watch(a)
  
  ## Function jiska derivative nikalna hai
  c = tf.sqrt(tf.square(a) + tf.square(b))
  
  ## Derivative of c with respect to a
  dc_da = tape.gradient(c, a)
  print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


For all variables. the calculation is tracked by default and used to find the gradient, so do not usetape.watch()

In [289]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c, a)
  print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


In [290]:
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c, a)
  d2c_da2 = outer_tape.gradient(dc_da, a)
  print(d2c_da2)

tf.Tensor(
[[0.14203143 0.3846457 ]
 [0.63471186 0.37015942]], shape=(2, 2), dtype=float32)
